const img1 = "./assets/svg/today-pick1.png";
const imga1 = "./assets/svg/today-pick1.png";
const img2 = "./assets/svg/today-pick2.png";
const imga2 = "./assets/svg/today-pick2.png";
const img3 = "./assets/svg/today-pick3.png";
const imga3 = "./assets/svg/today-pick3.png";
const img4 = "./assets/svg/today-pick4.png";
const imga4 = "./assets/svg/today-pick4.png";
const img5 = "./assets/svg/today-pick5.png";
const imga5 = "./assets/svg/today-pick5.png";
const img6 = "./assets/svg/today-pick6.png";
const imga6 = "./assets/svg/today-pick6.png";
const img7 = "./assets/svg/today-pick7.png";
const imga7 = "./assets/svg/today-pick7.png";
const img8 = "./assets/svg/today-pick8.png";
const imga8 = "./assets/svg/today-pick8.png";
const imgCollection1 = "./assets/images/avatar/avt-18.jpg";

const todayPickData = [
  {
    img: img1,
    title: "The RenaiXance Rising the sun ",
    tags: "bsc",
    imgAuthor: imga1,
    nameAuthor: "SalvadorDali",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img2,
    title: "Space babe - Night 2/25 ",
    tags: "bsc",
    imgAuthor: imga2,
    nameAuthor: "Trista Francis",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    feature: "coming soon",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img3,
    title: "CyberPrimal 042 LAN",
    tags: "bsc",
    imgAuthor: imga3,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img4,
    title: "Crypto Egg Stamp #5 ",
    tags: "bsc",
    imgAuthor: imga4,
    nameAuthor: "Tyler Covington",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img5,
    title: "Travel Monkey Club #45 ",
    tags: "bsc",
    imgAuthor: imga5,
    nameAuthor: "SalvadorDali",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img6,
    title: "Sir. Lion Swag #371 ",
    tags: "bsc",
    imgAuthor: imga6,
    nameAuthor: "Trista Francis",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img7,
    title: "Cyber Doberman #766",
    tags: "bsc",
    imgAuthor: imga7,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img8,
    title: "Living Vase 01 by Lanz...",
    tags: "bsc",
    imgAuthor: imga8,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img1,
    title: "The RenaiXance Rising the sun ",
    tags: "bsc",
    imgAuthor: imga1,
    nameAuthor: "SalvadorDali",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img2,
    title: "Space babe - Night 2/25 ",
    tags: "bsc",
    imgAuthor: imga2,
    nameAuthor: "Trista Francis",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    feature: "coming soon",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img3,
    title: "CyberPrimal 042 LAN",
    tags: "bsc",
    imgAuthor: imga3,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img4,
    title: "Crypto Egg Stamp #5 ",
    tags: "bsc",
    imgAuthor: imga4,
    nameAuthor: "Tyler Covington",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img5,
    title: "Travel Monkey Club #45 ",
    tags: "bsc",
    imgAuthor: imga5,
    nameAuthor: "SalvadorDali",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img6,
    title: "Sir. Lion Swag #371 ",
    tags: "bsc",
    imgAuthor: imga6,
    nameAuthor: "Trista Francis",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img7,
    title: "Cyber Doberman #766",
    tags: "bsc",
    imgAuthor: imga7,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
  {
    img: img8,
    title: "Living Vase 01 by Lanz...",
    tags: "bsc",
    imgAuthor: imga8,
    nameAuthor: "Freddie Carpenter",
    price: "4.89 SOL",
    priceChange: "$12.246",
    wishlist: "100",
    imgCollection: imgCollection1,
    nameCollection: "Creative Art 3D",
  },
];

export default todayPickData;
