import React, { Fragment, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Header from "../components/Layout/Header";
import Footer from "../components/Layout/Footer";
export default function Admin() {
  const redeemList = [{
    name: "John Doe",
    points: 3,
    address: "sgGYUFdf33F96dgxgRdtdgsdsd3SDD",
    img: "./assets/svg/today-pick6.png"
  },
  {
    name: "Jane Doe",
    points: 12,
    address: "sgGYUFdf33F96dgxgRdtdgsdsd3SDD",
    img: "./assets/svg/today-pick1.png"
  },
  {
    name: "Bruce Wayne",
    points: 90,
    address: "sgGYUFdf33F96dgxgRdtdgsdsd3SDD",
    img: "./assets/svg/today-pick3.png"
  },
  {
    name: "Wanda",
    points: 17,
    address: "sgGYUFdf33F96dgxgRdtdgsdsd3SDD",
    img: "./assets/svg/today-pick4.png"
  }
  ]
  return (
    <div>
      <Head>
        <title>Apes Planet | NFT Based Fighting Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./assets/icon/Favicon.png" />
      </Head>
      <div className="home-1">


        <Header />
        <Fragment>
          <section
            className="tf-section "
            style={{ position: "absolute", width: "100%", height: "100vh" }}
          >
            <div className="themesflat-container">
              <div className="row mt-4">
                <div className="col-md-12 text-center">
                  <h3 className="tf-title pb-20">Admin Panel</h3>
                </div>
              </div>
              <div className="row">
                <div className="col-lg-10 m-auto">
                  <div>
                    <h4 class="heading" style={{ color: "rgb(115, 222, 78)" }}>
                      Redeem Requests
                    </h4>
                  </div>
                  <div style={{ marginTop: "20px" }}>
                    <div class="client-infor sc-card-product">
                      {redeemList.map((item) => <>
                        <div class="meta-info redeem" style={{ cursor: "pointer" }}>
                          <div class="author"><div class="avatar"><img src={item.img} alt="Axies" /></div><div class="info"><span>Requested By</span><h6> <a href="#">{item.name}</a> </h6></div></div>

                          <div class="author"><div class="avatar"></div><div class="info"><span>Banana Points</span><h6> <a href="#" className="text-center" >{item.points}</a> </h6></div></div>
                          <div class="author"><div class="avatar"></div><div class="info"><span></span><h6> <a href="#" className="text-center" >{item.address}</a> </h6></div></div>
                          <div class="author"><div class="avatar"></div><div class="info"><span></span><h6>
                            <button class="sc-button pri-3 btn-sm">Transfer</button> </h6></div></div>
                        </div>
                        <br />
                      </>)}


                    </div>
                  </div>
                  <br />
                </div>
              </div>
            </div>
          </section>
        </Fragment>
      </div>
    </div>
  );
}
