import Head from "next/head";
import Header from "./../components/Layout/Header";
import Slider from "./../components/Slider/Slider";
import LiveAuction from "./../components/LiveAuction/LiveAuction";
import TopSeller from "./../components/TopSeller/TopSeller";
import TodayPicks from "./../components/TodayPicks/TodayPicks";
import PopularCollection from "./../components/PopularCollection/PopularCollection";
import Create from "./../components/Create/Create";
import Footer from "./../components/Layout/Footer";
import FixedNfts from "./../components/Fixed Nfts/FixedNfts";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Apes Planet | NFT Based Fighting Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./assets/icon/Favicon.png" />
      </Head>
      <div className="home-1">
        <img
          src={"./assets/svg/coin1.png"}
          className="first-coin"
          alt="bgimg"
        />
        <img
          src={"./assets/svg/coin2.png"}
          className="second-coin"
          alt="bgimg"
        />
        <img
          src={"./assets/svg/talwar.png"}
          className="talwar-svg"
          alt="bgimg"
        />

        <Header />
        <Slider />
        <LiveAuction />
        <FixedNfts />
        <TopSeller />
        <TodayPicks />
        <PopularCollection />
        <Create />
        <Footer />
      </div>
    </div>
  );
}
